# Generated by Django 3.2.15 on 2022-08-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iebc_region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pdfpath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_34_path', models.CharField(max_length=200)),
                ('polling_station_code', models.CharField(editable=False, max_length=900)),
                ('date_posted', models.DateTimeField(null=True)),
                ('iebc_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form34web.region')),
            ],
        ),
    ]
